.changeset/smart-weeks-sort.md, .prettierrc, .vscode/settings.json, README.md, eslint.config.js, packages/runed/README.md, packages/runed/src/lib/functions/box/box.svelte.ts, packages/runed/src/lib/functions/box/box.test.svelte.ts, pnpm-lock.yaml, sites/docs/content/functions/box.md, sites/docs/content/index.md
This PR adds a `box.readonly` utility function for converting boxes that may be writable to readable boxes.
=> feat: `box.readonly`

.changeset/tricky-suns-occur.md, packages/runed/src/lib/functions/index.ts, packages/runed/src/lib/functions/useActiveElement/useActiveElement.svelte.ts, packages/runed/src/lib/functions/useElementSize/useElementSize.svelte.ts, packages/runed/src/lib/functions/useMounted/useMounted.svelte.ts, packages/runed/src/lib/functions/useSupported/index.ts, packages/runed/src/lib/functions/useSupported/useSupported.svelte.ts, sites/docs/content/functions/use-supported.md, sites/docs/mdsx.config.js, sites/docs/src/lib/components/demos/use-supported.svelte, sites/docs/src/lib/config/navigation.ts
Determine if a specific API or whatever is available in the environment before attempting to use it.
=> feat: `useSupported`

.changeset/olive-rivers-try.md, packages/runed/src/lib/functions/useEventListener/useEventListener.svelte.ts, packages/runed/src/lib/internal/utils/event.ts
The overloads for `addEventListener` define the `event` parameter as a `string`, but the implementation define it as `string | string[]`.
This PR removes the unnecessary code needed to support `string[]`.
=> Cleanup addEventListener

sites/docs/content/utilities/watch.md
box is being referrenced in documentation about [watch](https://runed.dev/docs/utilities/watch).
=> remove reference to box in the site.

.changeset/new-bears-speak.md, packages/runed/src/lib/utilities/MediaQuery/MediaQuery.svelte.ts, packages/runed/src/lib/utilities/MediaQuery/index.ts, packages/runed/src/lib/utilities/index.ts, sites/docs/content/utilities/media-query.md, sites/docs/src/lib/components/demos/media-query.svelte
This adds a `MediaQuery` utility where you can pass a media query and get back true or false in case it matches (with reactivity).
You need to specifically pass the media query like this "(media-query-here)" so i was wondering if a warn in case the parentheses are not there could be a good thing. Maybe even add them automatically if not presents.
WDYT?
I did not add any test because for what i was able to see JSDom doesn't have a way to check media queries. I could mock that but i don't know if that's really useful.
Also also, i just created an effect in the constructor...this means it will likely fail if the instance is created in a `.svelte.ts` file. One possible way out of this could be to try to create the effect, if it fails wrap everything in `$effect.root` and expose a cleanup …
=> feat: add MediaQuery utility

.changeset/quick-foxes-end.md, packages/runed/src/lib/utilities/watch/index.ts, packages/runed/src/lib/utilities/watch/watch.svelte.ts, packages/runed/src/lib/utilities/watch/watch.test.svelte.ts
This PR changes two things about the `watch` helper.
1. Remove the `once: boolean` option in favor of a separate `watchOnce` function.
The default behavior for `watch` is to run immediately, unlike in Vue where it runs lazily when a dependency changes, so having `once: true` behave just like `onMount` by default makes no sense. As an added bonus, `watch` is now much simpler internally.
2. To watch for changes to multiple values, you pass an array of getters.
Previously, you would pass a getter to an array of state values, but this is kind of ambiguous. What if I want to watch for changes to a single state that happens to be an array?
```ts
let items = $state([]);
watch(() => items, (items, previousItems) => {
// `previousItems` is an empty array, but it should be `undefined`!
});
// …
```
=> feat: update `watch`

.changeset/config.json, sites/docs/CHANGELOG.md, sites/docs/package.json
undoing a failed attempt at redeploying docs site without cutting a new runed release
=> remove changesets from docs

.github/workflows/deploy-docs.yml
Used when we want to deploy an update to the documentation without a changeset being present.
=> chore: add manual deploy action

.changeset/hot-feet-hang.md, packages/runed/src/lib/utilities/MediaQuery/MediaQuery.svelte.ts
This fixes a bug someone opened in the svelte repo but it was actually our (namely **my** lol) bad.
EDIT: oh they also reported here... Closes #121 
https://github.com/sveltejs/svelte/issues/12571#issuecomment-2248328612
We should avoid writing to state in the getter but we can just leave the state undefined and return the actual value from mediaQuery list (it will still be reactive from the moment we register the listener since we are still accessing the signal to check if it's undefined).
EDIT: i've also changed effectRegistered to a number to handle the case where multiple components that access the same instance of the class mount in the same tick.
=> fix: avoid writing to state in media-query getter

.changeset/gentle-plants-tan.md, .changeset/young-comics-punch.md, eslint.config.js, packages/runed/src/lib/utilities/IsSupported/IsSupported.svelte.ts, packages/runed/src/lib/utilities/index.ts, packages/runed/src/lib/utilities/useGeolocation/index.ts, packages/runed/src/lib/utilities/useGeolocation/useGeolocation.svelte.ts, scripts/add-utility.mjs, sites/docs/src/content/utilities/is-supported.md, sites/docs/src/content/utilities/use-geolocation.md, sites/docs/src/lib/components/demos/use-geolocation.svelte
Reactive access to the browser's Geolocation API.
=> feat: `useGelocation`

.changeset/two-pianos-beg.md, packages/runed/src/lib/internal/utils/sleep.ts, packages/runed/src/lib/test/util.svelte.ts, packages/runed/src/lib/utilities/PersistedState/PersistedState.svelte.ts, packages/runed/src/lib/utilities/PersistedState/PersistedState.test.svelte.ts
Fixes #150.
jsdom doesn't raise the 'storage' event because this event only fires when values change **in a different** window, which is something we don't have (we only have one window).  So to unit-test, one must dispatch the event manually.
Also:  The event handler uses `getValueFromStorage` to obtain the value, but the `event.newValue` property already has this value.  This seems like an unnecessary performance hit, and may be best to simply deserialize `event.newValue`.
I noticed that there is no deletion.  I think that whenever `this.#current` becomes undefined, the value in storage should be deleted.
=> fix: only listen for the 'storage' event if using 'local' storage

.changeset/three-cups-watch.md, packages/runed/src/lib/utilities/useGeolocation/useGeolocation.svelte.ts, sites/docs/src/content/utilities/use-geolocation.md, sites/docs/src/lib/components/demos/use-geolocation.svelte
This PR changes the return type of `useGeolocation` to align with the return type of the Geolocation Web API for familiarity/consistency.
=> breaking: Align `useGeolocation` API with Web API

.changeset/clean-schools-sell.md, packages/runed/src/lib/internal/configurable-globals.ts
We started getting some issues with Astro static builds when updating to a version of Runed that has the `defaultWindow`, `defaultDocument`, etc.
=> patch: additional window checks for astro

sites/docs/src/content/utilities/on-click-outside.md
=> docs: rename binding variable from 'el' to 'container' in on-click-outside

sites/docs/src/content/utilities/state-history.md
Hi,
Based on the StateHistory example code it seems in the documentation wrong function is imported.
This PR fixes the docs to the correct one.
=> Correct StateHistory example usage in documentation

.changeset/calm-pumpkins-dress.md, packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts, packages/runed/src/lib/utilities/persisted-state/persisted-state.test.svelte.ts
Integrated Rich Harris's proxy solution to solve watching nested properties:
https://github.com/Rich-Harris/local-storage-test/blob/main/src/lib/storage.svelte.ts
Had to update existing tests as the getter for `current` always deserializes the state from storage.
=> fix(persisted-state): write state to storage even if only a nested property is changed. fixes #224

.changeset/spotty-seals-collect.md, .github/ISSUE_TEMPLATE/3-bug_report.yml, packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts, packages/runed/src/lib/utilities/persisted-state/persisted-state.test.svelte.ts
Fixes #235 
Adds tracking for `.#version` also ensures that `.#version` is incremented on storage events.
**Also**:
- Updated issue template to `runed` instead of `WithRunes`
=> fix: Fixes issue where `PersistedState` wouldn't update the `.current` value in runes mode

.changeset/beige-fishes-argue.md, .changeset/two-cameras-perform.md, packages/runed/src/lib/utilities/pressed-keys/pressed-keys.svelte.ts, sites/docs/src/content/utilities/pressed-keys.md
This PR addresses #230 and introduces an `onKey` method to register a callback to execute when a specified key combination is pressed.
I attempted to add a unit test but was not able to mock or spy on the `window` properly. 
The best approach is to use an actual browser with `@vitest/browser` and `playwright` instead of `jsdom` or `happy-dom`. However, this would introduce a lot of changes and a longer CI time, so I might create a separate PR for that.  
Closes #230
=> fix(pressed-keys): keys are not cleared after key combination is pressed

sites/docs/src/content/utilities/watch.md
Also use tabs like the rest of the example snippets
=> docs: Fix indent/syntax on watch examples

.github/workflows/build-preview.yml, .github/workflows/deploy-docs.yml, .github/workflows/deploy-preview.yml
The latest version of the Cloudflare adapter no longer includes a bundle step for the generated worker file. Bundling now occurs during the deploy step instead (`refined-cf-action` takes care of this). Because of this, we now need to upload the entire `.svelte-kit` build directory as an artifact (rather than just the `.svelte-kit/cloudflare` dir).
PS: The preview for this PR won't work until the changes of `deploy-preview.yml` is on `main`.
=> chore: update preview workflows

.changeset/five-baboons-speak.md, packages/runed/src/lib/utilities/element-size/element-size.svelte.ts
This allow users of `ElementSize` to use the class even outside of a tracking reactive context. It keeps track if the `ResizeObserver` is instantiated and has run at least once (in that case uses the value from the resize observer) or calculate the size of the element on the fly using `offsetWidth` and `offsetHeight` + the styles for padding and border in case of `options.box==='content-box'`.
This is a breaking change but should be a welcome one.
=> breaking: remove `initialSize` and calculate size before first resize

packages/runed/src/lib/test/util.svelte.ts, packages/runed/src/lib/utilities/extract/extract.test.svelte.ts, packages/runed/src/lib/utilities/is-idle/is-idle.test.svelte.ts
The `vitestSetTimeoutWrapper` waited for `timeout + 1`, but only advanced by `timeout`. This means the tick which the callback fires at, never happens.
The `IsIdle` tests have been "passing" because of this, but didn't actually run their assertions (the inner callback).
Also added some extra tests.
=> test: fix is-idle tests and add extract tests

sites/docs/src/content/utilities/watch.md
This PR updates the documentation links in watch.md from the Svelte 5 preview site to the stable Svelte documentation.
Changes
- Updated `$effect link` from svelte-5-preview.vercel.app to svelte.dev
- Updated `$effect.pre` link to use the stable documentation URL with proper anchor
These links were pointing to the preview documentation which is no longer the primary source now that Svelte 5 is stable.
=> docs: update links in watch.md to point to the updated links for Svelte documentation

.changeset/tidy-items-behave.md, packages/runed/src/lib/utilities/persisted-state/persisted-state.svelte.ts, packages/runed/src/lib/utilities/persisted-state/persisted-state.test.svelte.ts
I got nerd sniped by @TGlide yesterday so this is a small refactor...there's no need to have a separate `#version` as this is basically what `createSubscriber` is doing under the hood.
I also refactored the `proxy` function externally and made sure that the proxy weak map is not recreated everytime we read current. I've added 2 or 3 tests because i noticed that we were not testing the reactivity part at all. I think we should find a way to enforce this kind of tests in every utility because with create subscriber it's very easy to skip the reactivity part if you never use it in an effect that actually needs to rerun.
Please test this thoroughly, it should work perfectly fine and I did test it myself but since the test suite is kinda lacking a bit of manual testing would be good (also if …
=> fix: remove `#version` from persisted & don't recreate proxies
